name: Formatear Markdown

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write **/*.md"
          commit_message: "estilo{.md}: Prettier"
