name: Formatear Formularios

on:
  workflow_dispatch:
  push:
    paths:
      - "formularios/*.md"
  pull_request:
    paths:
      - "formularios/*.md"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Acondicionar git # Necesario para que git diff funcione correctamente con archivos UTF-8
        run:  git config --global core.quotepath off

      - uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 2

      - name: Agregar bloques de código a los formularios
        run: |
          IFS=$'\n' read -r -d '' -a files < <( git diff --name-only ${{ github.event.before }} ${{ github.sha }} && printf '\0' )

          for file in "${files[@]}"; do
                  if [[ $file == *.md ]]; then
                          python .github/scripts/agregar_bloque_math.py "$file"
                  fi
          done

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "workflow(formularios): Agregar bloques de código"

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write **/*.md"
          commit_message: "estilo{.md}: Prettier"
